# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ovpnbd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ee5bced4a0e42e09605133f964296c3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fac07ba9153345ceb1daf10000a4822a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ee5bced4a0e42e09605133f964296c3 }}/openvpn:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ovpnbd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b52cdf24e124841887a9482af410c09 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ee5bced4a0e42e09605133f964296c3 }}/openvpn:${{ github.sha }}'